apiVersion: v1
kind: Service
metadata:
  name: ml-service
  labels:
    name: ml-service
spec:
  type: LoadBalancer
  selector:
    app: ml-service
  ports:
    - name: http
      port: 8000
      targetPort: 80
